#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: "true"
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.MySQL5Dialect"
#  database:
#    driverClassName: "com.mysql.jdbc.Driver"
#  datasource:
#    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
#    username: "root"
#    password: "gjh1346"
#    testWhileIdle : "true"
#    validationQuery: "SELECT 1"

#server:
#  port: 8081

# delegate user authorization to authorizationserver
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
  
signing:
  key: 345345fsdgsf5345  



logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG
    